version: 1
disable_existing_loggers: true

formatters:
  json:
    format: '{"time":"%(asctime)s", "name":"%(name)s", "level":"%(levelname)s", "message":"%(message)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  customer_service:  # Match the name we used in main.py
    level: INFO
    handlers: [console]
    propagate: yes
  __main__:
    level: INFO
    handlers: [console]
    propagate: yes
  services.shared.kafka_broker:
    level: INFO
    handlers: [console]
    propagate: yes

root:
  level: INFO
  handlers: [console]
  propagate: no