apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-web
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff-web
  template:
    metadata:
      labels:
        app: bff-web
    spec:
      containers:
        - name: bff-web
          image: royc003/bookstore-api:1 
          env:
            - name: BOOKS_SERVICE_URL
              value: "http://book-service.bookstore-ns:3000"
            - name: CUSTOMERS_SERVICE_URL
              value: "http://customer-service.bookstore-ns:3000"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
