apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: royc003/bookstore-api:5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # Add probes
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 45  # Increased delay
            periodSeconds: 30        # Less frequent checks
            timeoutSeconds: 10       # More time for response
            failureThreshold: 5      # More failures allowed
          env:
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
