apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookstore-ns
spec:
  replicas: 1  # Critical for circuit breaker state consistency
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: royc003/bookstore-api:4
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: circuit-breaker-volume
              mountPath: /mnt/circuit
          env:
            - name: DB_HOST
              value: bookstore-db-dev.cluster-cdljphha5o85.us-east-1.rds.amazonaws.com
            - name: DB_USER
              value: Bookstore
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: Bookstore
      volumes:
        - name: circuit-breaker-volume
          emptyDir: {}
